
### Get all students

GET http://localhost:5000/students


### Get student by id

GET http://localhost:5000/students/1

### Create student
POST http://localhost:5000/students
content-type: application/json

{
    "id": 3,
    "course": "Computer Science",
    "name": "Fritz"
}

### Update student
PUT http://localhost:5000/students/1
content-type: application/json

{
    "id": 1,
    "course": "Computer Science",
    "name": "John"
}

### Delete student
DELETE http://localhost:5000/students/3