@host = webapi789.azurewebsites.net
#@host = 20.203.242.109

### Get all students

GET https://{{host}}/students


### Get student by id

GET http://{{host}}/students/1

### Create student
POST http://{{host}}/students
content-type: application/json

{
    "id": 3,
    "course": "Computer Science",
    "name": "Fritz"
}

### Update student
PUT http://{{host}}/students/1
content-type: application/json

{
    "id": 1,
    "course": "Computer Science",
    "name": "John"
}

### Delete student
DELETE http://{{host}}/students/3